GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/5

###
GET https://fullstack-part3-backend.fly.dev/api/persons

###
GET https://fullstack-part3-backend.fly.dev/info

###
GET https://fullstack-part3-backend.fly.dev/api/persons/1

###
GET https://fullstack-part3-backend.fly.dev/api/persons/5



